linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - depguard
    - exhaustivestruct
    - gochecknoglobals
    - ifshort
    - paralleltest
    - wsl


